import { TerraformConfig, TerraformResource } from "@tfkonf/core";

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsAllInfoTypes {
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsAllText {
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsRedactionColor {
  blue?: number;
  green?: number;
  red?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsSelectedInfoTypesInfoTypesSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsSelectedInfoTypesInfoTypes {
  name: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsSelectedInfoTypesInfoTypesSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsSelectedInfoTypes {
  info_types: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsSelectedInfoTypesInfoTypes[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransforms {
  all_info_types?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsAllInfoTypes;
  all_text?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsAllText;
  redaction_color?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsRedactionColor;
  selected_info_types?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransformsSelectedInfoTypes;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformations {
  transforms: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformationsTransforms[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsInfoTypesSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsInfoTypes {
  name: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsInfoTypesSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMaxDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMaxTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMax {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMaxDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMaxTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMinDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMinTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMin {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMinDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMinTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValue {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBuckets {
  max?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMax;
  min?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMin;
  replacement_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfig {
  buckets?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBuckets[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore {
  characters_to_skip?: string;
  common_characters_to_ignore?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCharacterMaskConfig {
  masking_character?: string;
  number_to_mask?: number;
  reverse_order?: boolean;
  characters_to_ignore?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigContext {
  name?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType {
  name?: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfig {
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigContext;
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey;
  surrogate_info_type?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfig {
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKey;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigContext {
  name?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType {
  name?: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig {
  common_alphabet?: string;
  custom_alphabet?: string;
  radix?: number;
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigContext;
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey;
  surrogate_info_type?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigContext {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfig {
  lower_bound_days: number;
  upper_bound_days: number;
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigContext;
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKey;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound {
  float_value?: number;
  integer_value?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound {
  float_value?: number;
  integer_value?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfig {
  bucket_size: number;
  lower_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound;
  upper_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationRedactConfig {
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: number;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValueDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfig {
  new_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceDictionaryConfigWordList {
  words: string[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceDictionaryConfig {
  word_list: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceDictionaryConfigWordList;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationTimePartConfig {
  part_to_extract?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformation {
  replace_with_info_type_config?: boolean;
  bucketing_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfig;
  character_mask_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCharacterMaskConfig;
  crypto_deterministic_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfig;
  crypto_hash_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfig;
  crypto_replace_ffx_fpe_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig;
  date_shift_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfig;
  fixed_size_bucketing_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfig;
  redact_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationRedactConfig;
  replace_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfig;
  replace_dictionary_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceDictionaryConfig;
  time_part_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformationTimePartConfig;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformations {
  info_types?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsInfoTypes[];
  primitive_transformation: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformationsPrimitiveTransformation;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformations {
  transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformationsTransformations[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsField {
  name?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsValueDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsValueTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditions {
  operator: string;
  field: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsField;
  value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditionsValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditions {
  conditions?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditionsConditions[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressions {
  logical_operator?: string;
  conditions?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressionsConditions;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsCondition {
  expressions?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsConditionExpressions;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsFields {
  name?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsInfoTypesSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsInfoTypes {
  name: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsInfoTypesSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMaxDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMaxTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMax {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMaxDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMaxTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMinDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMinTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMin {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMinDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMinTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValue {
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBuckets {
  max?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMax;
  min?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsMin;
  replacement_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfig {
  buckets: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfigBuckets[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore {
  characters_to_skip?: string;
  common_characters_to_ignore?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCharacterMaskConfig {
  masking_character?: string;
  number_to_mask?: number;
  reverse_order?: boolean;
  characters_to_ignore?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigContext {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType {
  name: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfig {
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigContext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey;
  surrogate_info_type: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfig {
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfigCryptoKey;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigContext {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType {
  name: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig {
  common_alphabet?: string;
  custom_alphabet?: string;
  radix?: number;
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigContext;
  crypto_key: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey;
  surrogate_info_type?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigContext {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfig {
  lower_bound_days: number;
  upper_bound_days: number;
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigContext;
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfigCryptoKey;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound {
  float_value?: number;
  integer_value?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound {
  float_value?: number;
  integer_value?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfig {
  bucket_size: number;
  lower_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound;
  upper_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationRedactConfig {
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValueDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfig {
  new_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfigNewValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceDictionaryConfigWordList {
  words: string[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceDictionaryConfig {
  word_list: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceDictionaryConfigWordList;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceWithInfoTypeConfig {
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationTimePartConfig {
  part_to_extract: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformation {
  bucketing_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationBucketingConfig;
  character_mask_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCharacterMaskConfig;
  crypto_deterministic_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoDeterministicConfig;
  crypto_hash_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoHashConfig;
  crypto_replace_ffx_fpe_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig;
  date_shift_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationDateShiftConfig;
  fixed_size_bucketing_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationFixedSizeBucketingConfig;
  redact_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationRedactConfig;
  replace_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceConfig;
  replace_dictionary_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceDictionaryConfig;
  replace_with_info_type_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationReplaceWithInfoTypeConfig;
  time_part_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformationTimePartConfig;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformations {
  info_types?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsInfoTypes[];
  primitive_transformation: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformationsPrimitiveTransformation;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformations {
  transformations: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformationsTransformations[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMaxDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMaxTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMax {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMaxDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMaxTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMinDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMinTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMin {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMinDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMinTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValueTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBuckets {
  max?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMax;
  min?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsMin;
  replacement_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBucketsReplacementValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfig {
  buckets?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfigBuckets[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore {
  characters_to_skip?: string;
  common_characters_to_ignore?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCharacterMaskConfig {
  masking_character?: string;
  number_to_mask?: number;
  reverse_order?: boolean;
  characters_to_ignore?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCharacterMaskConfigCharactersToIgnore[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigContext {
  name?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType {
  name?: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoTypeSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfig {
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigContext;
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigCryptoKey;
  surrogate_info_type?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfigSurrogateInfoType;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfig {
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfigCryptoKey;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigContext {
  name?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore {
  score: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType {
  name?: string;
  version?: string;
  sensitivity_score?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoTypeSensitivityScore;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig {
  common_alphabet?: string;
  custom_alphabet?: string;
  radix?: number;
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigContext;
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigCryptoKey;
  surrogate_info_type?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfigSurrogateInfoType;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigContext {
  name?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped {
  crypto_key_name: string;
  wrapped_key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyTransient {
  name: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyUnwrapped {
  key: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKey {
  kms_wrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyKmsWrapped;
  transient?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyTransient;
  unwrapped?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKeyUnwrapped;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfig {
  lower_bound_days: number;
  upper_bound_days: number;
  context?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigContext;
  crypto_key?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfigCryptoKey;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBoundDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBoundTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBoundDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBoundTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBoundDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBoundTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBoundDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBoundTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfig {
  bucket_size: number;
  lower_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigLowerBound;
  upper_bound: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfigUpperBound;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationRedactConfig {
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValueDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValueTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfig {
  new_value: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfigNewValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceDictionaryConfigWordList {
  words: string[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceDictionaryConfig {
  word_list?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceDictionaryConfigWordList;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationTimePartConfig {
  part_to_extract?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformation {
  bucketing_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationBucketingConfig;
  character_mask_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCharacterMaskConfig;
  crypto_deterministic_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoDeterministicConfig;
  crypto_hash_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoHashConfig;
  crypto_replace_ffx_fpe_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationCryptoReplaceFfxFpeConfig;
  date_shift_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationDateShiftConfig;
  fixed_size_bucketing_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationFixedSizeBucketingConfig;
  redact_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationRedactConfig;
  replace_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceConfig;
  replace_dictionary_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationReplaceDictionaryConfig;
  time_part_config?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformationTimePartConfig;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformations {
  condition?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsCondition;
  fields: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsFields[];
  info_type_transformations?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsInfoTypeTransformations;
  primitive_transformation?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformationsPrimitiveTransformation;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditionsField {
  name?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditionsValueDateValue {
  day?: number;
  month?: number;
  year?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditionsValueTimeValue {
  hours?: number;
  minutes?: number;
  nanos?: number;
  seconds?: number;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditionsValue {
  boolean_value?: boolean;
  day_of_week_value?: string;
  float_value?: number;
  integer_value?: string;
  string_value?: string;
  timestamp_value?: string;
  date_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditionsValueDateValue;
  time_value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditionsValueTimeValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditions {
  operator: string;
  field: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditionsField;
  value?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditionsValue;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditions {
  conditions?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditionsConditions[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressions {
  logical_operator?: string;
  conditions?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressionsConditions;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsCondition {
  expressions?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsConditionExpressions;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressions {
  condition?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressionsCondition;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformations {
  field_transformations?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsFieldTransformations[];
  record_suppressions?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformationsRecordSuppressions[];
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfig {
  image_transformations?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigImageTransformations;
  info_type_transformations?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigInfoTypeTransformations;
  record_transformations?: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfigRecordTransformations;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgsTimeouts {
  create?: string;
  delete?: string;
  update?: string;
}

export interface GoogleDataLossPreventionDeidentifyTemplateArgs {
  description?: string;
  display_name?: string;
  parent: string;
  deidentify_config: GoogleDataLossPreventionDeidentifyTemplateArgsDeidentifyConfig;
  timeouts?: GoogleDataLossPreventionDeidentifyTemplateArgsTimeouts;
}

export class google_data_loss_prevention_deidentify_template extends TerraformResource {
  constructor(terraformConfig: TerraformConfig, resourceName: string, args: GoogleDataLossPreventionDeidentifyTemplateArgs) {
    const meta = {deidentify_config:{isBlock:true,image_transformations:{isBlock:true,transforms:{isBlock:true,all_info_types:{isBlock:true},all_text:{isBlock:true},redaction_color:{isBlock:true},selected_info_types:{isBlock:true,info_types:{isBlock:true,sensitivity_score:{isBlock:true}}}}},info_type_transformations:{isBlock:true,transformations:{isBlock:true,info_types:{isBlock:true,sensitivity_score:{isBlock:true}},primitive_transformation:{isBlock:true,bucketing_config:{isBlock:true,buckets:{isBlock:true,max:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}},min:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}},replacement_value:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}}},character_mask_config:{isBlock:true,characters_to_ignore:{isBlock:true}},crypto_deterministic_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}},surrogate_info_type:{isBlock:true,sensitivity_score:{isBlock:true}}},crypto_hash_config:{isBlock:true,crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}}},crypto_replace_ffx_fpe_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}},surrogate_info_type:{isBlock:true,sensitivity_score:{isBlock:true}}},date_shift_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}}},fixed_size_bucketing_config:{isBlock:true,lower_bound:{isBlock:true},upper_bound:{isBlock:true}},redact_config:{isBlock:true},replace_config:{isBlock:true,new_value:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}},replace_dictionary_config:{isBlock:true,word_list:{isBlock:true}},time_part_config:{isBlock:true}}}},record_transformations:{isBlock:true,field_transformations:{isBlock:true,condition:{isBlock:true,expressions:{isBlock:true,conditions:{isBlock:true,conditions:{isBlock:true,field:{isBlock:true},value:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}}}}},fields:{isBlock:true},info_type_transformations:{isBlock:true,transformations:{isBlock:true,info_types:{isBlock:true,sensitivity_score:{isBlock:true}},primitive_transformation:{isBlock:true,bucketing_config:{isBlock:true,buckets:{isBlock:true,max:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}},min:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}},replacement_value:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}}},character_mask_config:{isBlock:true,characters_to_ignore:{isBlock:true}},crypto_deterministic_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}},surrogate_info_type:{isBlock:true,sensitivity_score:{isBlock:true}}},crypto_hash_config:{isBlock:true,crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}}},crypto_replace_ffx_fpe_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}},surrogate_info_type:{isBlock:true,sensitivity_score:{isBlock:true}}},date_shift_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}}},fixed_size_bucketing_config:{isBlock:true,lower_bound:{isBlock:true},upper_bound:{isBlock:true}},redact_config:{isBlock:true},replace_config:{isBlock:true,new_value:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}},replace_dictionary_config:{isBlock:true,word_list:{isBlock:true}},replace_with_info_type_config:{isBlock:true},time_part_config:{isBlock:true}}}},primitive_transformation:{isBlock:true,bucketing_config:{isBlock:true,buckets:{isBlock:true,max:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}},min:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}},replacement_value:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}}},character_mask_config:{isBlock:true,characters_to_ignore:{isBlock:true}},crypto_deterministic_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}},surrogate_info_type:{isBlock:true,sensitivity_score:{isBlock:true}}},crypto_hash_config:{isBlock:true,crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}}},crypto_replace_ffx_fpe_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}},surrogate_info_type:{isBlock:true,sensitivity_score:{isBlock:true}}},date_shift_config:{isBlock:true,context:{isBlock:true},crypto_key:{isBlock:true,kms_wrapped:{isBlock:true},transient:{isBlock:true},unwrapped:{isBlock:true}}},fixed_size_bucketing_config:{isBlock:true,lower_bound:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}},upper_bound:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}},redact_config:{isBlock:true},replace_config:{isBlock:true,new_value:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}},replace_dictionary_config:{isBlock:true,word_list:{isBlock:true}},time_part_config:{isBlock:true}}},record_suppressions:{isBlock:true,condition:{isBlock:true,expressions:{isBlock:true,conditions:{isBlock:true,conditions:{isBlock:true,field:{isBlock:true},value:{isBlock:true,date_value:{isBlock:true},time_value:{isBlock:true}}}}}}}}},timeouts:{isBlock:true}};
    super(terraformConfig, "resource", args, meta, "google_data_loss_prevention_deidentify_template", resourceName);
  }

  get create_time(): string {
    return `${this.resourceType}.${this.resourceName}.create_time`;
  }

  get id(): string {
    return `${this.resourceType}.${this.resourceName}.id`;
  }

  get name(): string {
    return `${this.resourceType}.${this.resourceName}.name`;
  }

  get parent(): string {
    return `${this.resourceType}.${this.resourceName}.parent`;
  }

  get template_id(): string {
    return `${this.resourceType}.${this.resourceName}.template_id`;
  }

  get update_time(): string {
    return `${this.resourceType}.${this.resourceName}.update_time`;
  }
}
